# Generated by Django 4.0.3 on 2024-02-02 07:55

import diary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateDiary',
            fields=[
                ('diary_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('weather', models.CharField(max_length=30)),
                ('mood', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True)),
                ('reflection', models.CharField(blank=True, max_length=200, null=True)),
                ('praise', models.CharField(blank=True, max_length=200, null=True)),
                ('disclose', models.CharField(choices=[('public', '공개'), ('private', '비공개')], default='public', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.creatediary')),
            ],
        ),
    ]
