# Generated by Django 4.0.3 on 2024-02-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatediary',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
