# Generated by Django 4.0.3 on 2024-02-08 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0004_alter_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatediary',
            name='voter',
            field=models.ManyToManyField(related_name='voter_diary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creatediary',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_diary', to=settings.AUTH_USER_MODEL),
        ),
    ]
