# Generated by Django 4.0.3 on 2024-02-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_creatediary_voter_alter_creatediary_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatediary',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='diary_photo/'),
        ),
    ]
