# Generated by Django 4.0.3 on 2024-02-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_alter_creatediary_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatediary',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
